/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ff9159",
        "primary-dim": "#ff7524",
        "primary-container": "#ff7a2f",
        "primary-fixed": "#ff7a2f",
        "primary-fixed-dim": "#f66700",
        "on-primary": "#531e00",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#401500",
        "on-primary-fixed-variant": "#4f1c00",
        "secondary": "#f88d36",
        "secondary-dim": "#eb832c",
        "secondary-container": "#944a00",
        "secondary-fixed": "#ffc69f",
        "secondary-fixed-dim": "#ffb37d",
        "on-secondary": "#462000",
        "on-secondary-fixed": "#552800",
        "on-secondary-container": "#fff6f2",
        "on-secondary-fixed-variant": "#803f00",
        "tertiary": "#ffc562",
        "tertiary-dim": "#eba60f",
        "tertiary-container": "#fbb423",
        "tertiary-fixed": "#fbb423",
        "tertiary-fixed-dim": "#eba60f",
        "on-tertiary": "#5e4000",
        "on-tertiary-fixed": "#372400",
        "on-tertiary-container": "#523700",
        "on-tertiary-fixed-variant": "#5e4000",
        "error": "#ff7351",
        "error-dim": "#d53d18",
        "error-container": "#b92902",
        "on-error": "#450900",
        "on-error-container": "#ffd2c8",
        "surface": "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-variant": "#262626",
        "surface-container": "#191919",
        "surface-container-low": "#131313",
        "surface-container-high": "#1f1f1f",
        "surface-container-highest": "#262626",
        "surface-container-lowest": "#000000",
        "surface-tint": "#ff9159",
        "on-surface": "#ffffff",
        "on-surface-variant": "#ababab",
        "on-background": "#ffffff",
        "background": "#0e0e0e",
        "outline": "#757575",
        "outline-variant": "#484848",
        "inverse-surface": "#f9f9f9",
        "inverse-on-surface": "#555555",
        "inverse-primary": "#a14100",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      animation: {
        marquee: "marquee 20s linear infinite",
        "pulse-slow": "pulse 3s ease-in-out infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
};
